apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
data:
  SERVER_PORT: "8080"
  ENVIRONMENT: "production"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "taskmanager"
  POSTGRES_SSL_MODE: "require"
  MONGO_URI: "mongodb://mongodb-service:27017"
  MONGO_DB: "taskmanager"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_USER: "hamfa"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: ""
