apiVersion: v2
name: task-manager
description: A Helm chart for Task Manager API - DevOps Portfolio Project
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: hamfa
keywords:
  - golang
  - api
  - task-manager
  - devops
